Pop-Up Modal
mprotic123/mprotic123.github.io pull request #20
Opened 2021-10-06 14:45 UTC by mprotic123

Pull request created in order to review the project "Pop-Up modal" from Microverse.

2021-10-06 16:12 UTC, carlos-ssh requested changes
Hi @mprotic123 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-06 16:12 UTC, carlos-ssh commented on personal-portfolio/js/localstorage.js
> +
## Your projects should be in an array of objects. Kindly work on it.

![Screen Shot 2021-10-06 at 11 07 18](https://user-images.githubusercontent.com/22258274/136241822-92fd7311-6248-4dc2-a354-9e12e10103f6.png)

## Fix your linter issues instead disable many rules:
![Screen Shot 2021-10-06 at 11 09 26](https://user-images.githubusercontent.com/22258274/136242087-13dff122-8c57-4d6e-a894-663c2deb94ae.png)

2021-10-06 16:12 UTC, carlos-ssh commented on personal-portfolio/js/localstorage.js
> +
## Kindly fix your design issue:
- This container is overlapping ``x-axis``.
![Screen Shot 2021-10-06 at 11 05 41](https://user-images.githubusercontent.com/22258274/136242368-650570da-84e6-4cee-89fc-58984c26ab50.png)

2021-10-06 16:12 UTC, carlos-ssh commented on personal-portfolio/js/localstorage.js
> +
Provide a link to your License in your ``README`` file.

2021-10-08 10:37 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Milan Protić, 
 ### Thank you for working on the changes suggested. :ok_hand:

## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-08 10:37 UTC, SajjadAhmad14 commented on personal-portfolio/css/style.css
Pop-up still does not follow the design on both desktop and mobile. `See live` and `See Source` buttons should be on the right side of the project title. The mobile view does not show these buttons. Kindly make the necessary changes while following the design exactly
![btns](https://user-images.githubusercontent.com/35504149/136542339-87cc395d-d691-4b13-b1af-97e0a0d316a5.png)
.

2021-10-08 16:22 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Milan Protić, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏
# OPTIONAL BUT RECOMMENDED
## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-08 16:22 UTC, SajjadAhmad14 commented on personal-portfolio/css/style.css
>  #icon-1 {
[ OPTIONAL ] Please add an icon to the `See source` button on the mobile view
![optional](https://user-images.githubusercontent.com/35504149/136590687-6a65a0f5-432d-4bd7-9772-595d7f9cacf5.png)

2021-10-08 16:26 UTC, closed without merging

2021-10-08 16:26 UTC, mprotic123 commented
Pull request approved.